name: Run Unit Tests via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies for each environment
      run: |
        python -m pip install --upgrade pip
        python -m venv --upgrade-deps core_only
        source core_only/bin/activate
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install coverage[toml] pytest
        deactivate
    - name: Clone nubs
      uses: actions/checkout@v4
      with:
        repository: DStauffman/nubs
        path: ${{ github.workspace }}/nubs_repo
    - name: Clone slog
      uses: actions/checkout@v4
      with:
        repository: DStauffman/slog
        path: ${{ github.workspace }}/slog_repo
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${{ github.workspace }}/nubs_repo:${{ github.workspace }}/slog_repo" >> "$GITHUB_ENV"
    - name: Test core_only with pytest
      run: |
        pwd
        ls -l
        echo $PYTHONPATH
        source core_only/bin/activate
        python -m dstauffman tests
